server.port=8087
spring.application.name=ms-reportes

# 🔄 Cambiado a 3309 para evitar chocar con el contenedor de pagos
spring.datasource.url=jdbc:mysql://localhost:3309/db_reportes?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=system
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false